export const DIAN_MUNICIPALITIES = [
  { code: 1, name: "Bogotá D.C.", department: "Bogotá D.C." },
  { code: 5, name: "Medellín", department: "Antioquia" },
  { code: 11, name: "Cali", department: "Valle del Cauca" },
  { code: 149, name: "Barranquilla", department: "Atlántico" },
  { code: 150, name: "Cartagena", department: "Bolívar" },
  { code: 17, name: "Bucaramanga", department: "Santander" },
  { code: 41, name: "Cúcuta", department: "Norte de Santander" },
  { code: 52, name: "Ibagué", department: "Tolima" },
  { code: 54, name: "Pereira", department: "Risaralda" },
  { code: 66, name: "Manizales", department: "Caldas" },
  { code: 68, name: "Santa Marta", department: "Magdalena" },
  { code: 73, name: "Villavicencio", department: "Meta" },
  { code: 76, name: "Pasto", department: "Nariño" },
  { code: 81, name: "Armenia", department: "Quindío" },
  { code: 85, name: "Neiva", department: "Huila" },
  { code: 86, name: "Montería", department: "Córdoba" },
  { code: 88, name: "Popayán", department: "Cauca" },
  { code: 91, name: "Sincelejo", department: "Sucre" },
  { code: 94, name: "Valledupar", department: "Cesar" },
  { code: 97, name: "Tunja", department: "Boyacá" },
  { code: 99, name: "Riohacha", department: "La Guajira" },
  { code: 101, name: "Florencia", department: "Caquetá" },
  { code: 105, name: "Quibdó", department: "Chocó" },
  { code: 108, name: "Yopal", department: "Casanare" },
  { code: 111, name: "Mocoa", department: "Putumayo" },
  { code: 113, name: "Leticia", department: "Amazonas" },
  { code: 115, name: "Arauca", department: "Arauca" },
  { code: 118, name: "Puerto Carreño", department: "Vichada" },
  { code: 120, name: "Inírida", department: "Guainía" },
  { code: 122, name: "Mitú", department: "Vaupés" },
  { code: 124, name: "San José del Guaviare", department: "Guaviare" },
  { code: 130, name: "Soacha", department: "Cundinamarca" },
  { code: 132, name: "Soledad", department: "Atlántico" },
  { code: 134, name: "Bello", department: "Antioquia" },
  { code: 136, name: "Itagüí", department: "Antioquia" },
  { code: 138, name: "Envigado", department: "Antioquia" },
  { code: 140, name: "Buenaventura", department: "Valle del Cauca" },
  { code: 142, name: "Palmira", department: "Valle del Cauca" },
  { code: 144, name: "Floridablanca", department: "Santander" },
  { code: 146, name: "Girón", department: "Santander" },
  { code: 148, name: "Piedecuesta", department: "Santander" },
  { code: 152, name: "Dosquebradas", department: "Risaralda" },
  { code: 154, name: "Tuluá", department: "Valle del Cauca" },
  { code: 156, name: "Apartadó", department: "Antioquia" },
  { code: 158, name: "Barrancabermeja", department: "Santander" },
  { code: 160, name: "Zipaquirá", department: "Cundinamarca" },
  { code: 162, name: "Facatativá", department: "Cundinamarca" },
  { code: 164, name: "Chía", department: "Cundinamarca" },
  { code: 166, name: "Fusagasugá", department: "Cundinamarca" },
  { code: 168, name: "Girardot", department: "Cundinamarca" },
  { code: 170, name: "Sogamoso", department: "Boyacá" },
  { code: 172, name: "Duitama", department: "Boyacá" },
  { code: 174, name: "Ocaña", department: "Norte de Santander" },
  { code: 176, name: "Ciénaga", department: "Magdalena" },
  { code: 178, name: "Maicao", department: "La Guajira" },
  { code: 180, name: "Turbo", department: "Antioquia" },
  { code: 182, name: "Aguachica", department: "Cesar" },
  { code: 184, name: "Magangué", department: "Bolívar" },
  { code: 186, name: "Lorica", department: "Córdoba" },
  { code: 188, name: "Cereté", department: "Córdoba" },
  { code: 190, name: "Sahagún", department: "Córdoba" },
  { code: 192, name: "Rionegro", department: "Antioquia" },
  { code: 194, name: "Caucasia", department: "Antioquia" },
  { code: 196, name: "Cartago", department: "Valle del Cauca" },
  { code: 198, name: "Buga", department: "Valle del Cauca" },
  { code: 200, name: "Yumbo", department: "Valle del Cauca" },
  { code: 202, name: "Jamundí", department: "Valle del Cauca" },
  { code: 204, name: "Malambo", department: "Atlántico" },
  { code: 206, name: "Turbaco", department: "Bolívar" },
  { code: 208, name: "Sabanalarga", department: "Atlántico" },
  { code: 210, name: "Madrid", department: "Cundinamarca" },
  { code: 212, name: "Mosquera", department: "Cundinamarca" },
  { code: 214, name: "Funza", department: "Cundinamarca" },
  { code: 216, name: "Cajicá", department: "Cundinamarca" },
  { code: 218, name: "La Ceja", department: "Antioquia" },
  { code: 220, name: "Marinilla", department: "Antioquia" },
  { code: 222, name: "El Carmen de Viboral", department: "Antioquia" },
  { code: 224, name: "Caldas", department: "Antioquia" },
  { code: 226, name: "Sabaneta", department: "Antioquia" },
  { code: 228, name: "La Estrella", department: "Antioquia" },
  { code: 230, name: "Copacabana", department: "Antioquia" },
  { code: 232, name: "Barbosa", department: "Antioquia" },
  { code: 999, name: "Otro / No Especificado", department: "Otros" },
] as const;

export type DianMunicipalityCode = typeof DIAN_MUNICIPALITIES[number]["code"];

export function getMunicipalityName(code: number): string {
  const municipality = DIAN_MUNICIPALITIES.find(m => m.code === code);
  return municipality ? `${municipality.name}, ${municipality.department}` : String(code);
}
