export const DIAN_COUNTRIES = [
  { code: "013", name: "Afganistán" },
  { code: "017", name: "Albania" },
  { code: "023", name: "Alemania" },
  { code: "026", name: "Armenia" },
  { code: "027", name: "Aruba" },
  { code: "029", name: "Bosnia-Herzegovina" },
  { code: "031", name: "Burkina Fasso" },
  { code: "037", name: "Andorra" },
  { code: "040", name: "Angola" },
  { code: "041", name: "Anguilla" },
  { code: "043", name: "Antigua y Barbuda" },
  { code: "047", name: "Antillas Holandesas" },
  { code: "053", name: "Arabia Saudita" },
  { code: "059", name: "Argelia" },
  { code: "063", name: "Argentina" },
  { code: "069", name: "Australia" },
  { code: "072", name: "Austria" },
  { code: "074", name: "Azerbaijan" },
  { code: "077", name: "Bahamas" },
  { code: "080", name: "Bahrein" },
  { code: "081", name: "Bangladesh" },
  { code: "083", name: "Barbados" },
  { code: "087", name: "Bélgica" },
  { code: "088", name: "Belice" },
  { code: "090", name: "Bermudas" },
  { code: "091", name: "Belarus" },
  { code: "093", name: "Birmania (Myanmar)" },
  { code: "097", name: "Bolivia" },
  { code: "101", name: "Botswana" },
  { code: "105", name: "Brasil" },
  { code: "108", name: "Brunei Darussalam" },
  { code: "111", name: "Bulgaria" },
  { code: "115", name: "Burundi" },
  { code: "119", name: "Bután" },
  { code: "127", name: "Cabo Verde" },
  { code: "137", name: "Caimán, Islas" },
  { code: "141", name: "Camboya (Kampuchea)" },
  { code: "145", name: "Camerún" },
  { code: "149", name: "Canadá" },
  { code: "159", name: "Santa Sede" },
  { code: "165", name: "Cocos (Keeling), Islas" },
  { code: "45", name: "Colombia" },
  { code: "173", name: "Comoras" },
  { code: "177", name: "Congo" },
  { code: "183", name: "Cook, Islas" },
  { code: "187", name: "Corea del Norte" },
  { code: "190", name: "Corea del Sur" },
  { code: "193", name: "Costa de Marfil" },
  { code: "196", name: "Costa Rica" },
  { code: "198", name: "Croacia" },
  { code: "199", name: "Cuba" },
  { code: "203", name: "Chad" },
  { code: "211", name: "Chile" },
  { code: "215", name: "China" },
  { code: "218", name: "Taiwán (Formosa)" },
  { code: "221", name: "Chipre" },
  { code: "229", name: "Benin" },
  { code: "232", name: "Dinamarca" },
  { code: "235", name: "Dominica" },
  { code: "239", name: "Ecuador" },
  { code: "240", name: "Egipto" },
  { code: "242", name: "El Salvador" },
  { code: "243", name: "Eritrea" },
  { code: "244", name: "Emiratos Árabes Unidos" },
  { code: "245", name: "España" },
  { code: "246", name: "Eslovaquia" },
  { code: "247", name: "Eslovenia" },
  { code: "249", name: "Estados Unidos" },
  { code: "251", name: "Estonia" },
  { code: "253", name: "Etiopía" },
  { code: "259", name: "Feroe, Islas" },
  { code: "267", name: "Filipinas" },
  { code: "271", name: "Finlandia" },
  { code: "275", name: "Francia" },
  { code: "281", name: "Gabón" },
  { code: "285", name: "Gambia" },
  { code: "287", name: "Georgia" },
  { code: "289", name: "Ghana" },
  { code: "293", name: "Gibraltar" },
  { code: "297", name: "Granada" },
  { code: "301", name: "Grecia" },
  { code: "305", name: "Groenlandia" },
  { code: "309", name: "Guadalupe" },
  { code: "313", name: "Guam" },
  { code: "317", name: "Guatemala" },
  { code: "325", name: "Guayana Francesa" },
  { code: "329", name: "Guinea" },
  { code: "331", name: "Guinea Ecuatorial" },
  { code: "334", name: "Guinea-Bissau" },
  { code: "337", name: "Guyana" },
  { code: "341", name: "Haití" },
  { code: "345", name: "Honduras" },
  { code: "351", name: "Hong Kong" },
  { code: "355", name: "Hungría" },
  { code: "361", name: "India" },
  { code: "365", name: "Indonesia" },
  { code: "369", name: "Irak" },
  { code: "372", name: "Irán" },
  { code: "375", name: "Irlanda" },
  { code: "379", name: "Islandia" },
  { code: "383", name: "Israel" },
  { code: "386", name: "Italia" },
  { code: "391", name: "Jamaica" },
  { code: "399", name: "Japón" },
  { code: "403", name: "Jordania" },
  { code: "406", name: "Kazajstán" },
  { code: "410", name: "Kenia" },
  { code: "411", name: "Kiribati" },
  { code: "412", name: "Kirguizistán" },
  { code: "413", name: "Kuwait" },
  { code: "420", name: "Laos" },
  { code: "426", name: "Lesotho" },
  { code: "429", name: "Letonia" },
  { code: "431", name: "Líbano" },
  { code: "434", name: "Liberia" },
  { code: "438", name: "Libia" },
  { code: "440", name: "Liechtenstein" },
  { code: "443", name: "Lituania" },
  { code: "445", name: "Luxemburgo" },
  { code: "447", name: "Macao" },
  { code: "448", name: "Macedonia" },
  { code: "450", name: "Madagascar" },
  { code: "455", name: "Malaysia" },
  { code: "458", name: "Malawi" },
  { code: "461", name: "Maldivas" },
  { code: "464", name: "Mali" },
  { code: "467", name: "Malta" },
  { code: "469", name: "Marianas del Norte, Islas" },
  { code: "472", name: "Marshall, Islas" },
  { code: "474", name: "Marruecos" },
  { code: "477", name: "Martinica" },
  { code: "485", name: "Mauricio" },
  { code: "488", name: "Mauritania" },
  { code: "493", name: "México" },
  { code: "494", name: "Micronesia" },
  { code: "496", name: "Moldavia" },
  { code: "497", name: "Mongolia" },
  { code: "498", name: "Mónaco" },
  { code: "501", name: "Monserrat, Isla" },
  { code: "505", name: "Mozambique" },
  { code: "507", name: "Namibia" },
  { code: "508", name: "Nauru" },
  { code: "511", name: "Navidad (Christmas), Islas" },
  { code: "517", name: "Nepal" },
  { code: "521", name: "Nicaragua" },
  { code: "525", name: "Níger" },
  { code: "528", name: "Nigeria" },
  { code: "531", name: "Niue, Isla" },
  { code: "535", name: "Norfolk, Isla" },
  { code: "538", name: "Noruega" },
  { code: "542", name: "Nueva Caledonia" },
  { code: "545", name: "Papuasia Nueva Guinea" },
  { code: "548", name: "Nueva Zelandia" },
  { code: "551", name: "Vanuatu" },
  { code: "556", name: "Omán" },
  { code: "566", name: "Pacífico, Islas (USA)" },
  { code: "573", name: "Países Bajos (Holanda)" },
  { code: "576", name: "Pakistán" },
  { code: "578", name: "Palau, Islas" },
  { code: "580", name: "Panamá" },
  { code: "586", name: "Paraguay" },
  { code: "589", name: "Perú" },
  { code: "593", name: "Pitcairn, Isla" },
  { code: "599", name: "Polinesia Francesa" },
  { code: "603", name: "Polonia" },
  { code: "607", name: "Portugal" },
  { code: "611", name: "Puerto Rico" },
  { code: "618", name: "Qatar" },
  { code: "628", name: "Reino Unido" },
  { code: "640", name: "República Centroafricana" },
  { code: "644", name: "República Checa" },
  { code: "647", name: "República Dominicana" },
  { code: "660", name: "Reunión" },
  { code: "665", name: "Zimbabwe" },
  { code: "670", name: "Rumania" },
  { code: "675", name: "Ruanda" },
  { code: "676", name: "Rusia" },
  { code: "677", name: "Salomón, Islas" },
  { code: "685", name: "Sahara Occidental" },
  { code: "687", name: "Samoa" },
  { code: "690", name: "Samoa Norteamericana" },
  { code: "695", name: "San Cristóbal y Nieves" },
  { code: "697", name: "San Marino" },
  { code: "700", name: "San Pedro y Miguelón" },
  { code: "705", name: "San Vicente y las Granadinas" },
  { code: "710", name: "Santa Elena" },
  { code: "715", name: "Santa Lucía" },
  { code: "720", name: "Santo Tomé y Príncipe" },
  { code: "728", name: "Senegal" },
  { code: "731", name: "Seychelles" },
  { code: "735", name: "Sierra Leona" },
  { code: "741", name: "Singapur" },
  { code: "744", name: "Siria" },
  { code: "748", name: "Somalia" },
  { code: "750", name: "Sri Lanka" },
  { code: "756", name: "Sudáfrica" },
  { code: "759", name: "Sudán" },
  { code: "764", name: "Suecia" },
  { code: "767", name: "Suiza" },
  { code: "770", name: "Surinam" },
  { code: "773", name: "Swazilandia" },
  { code: "774", name: "Tadjikistán" },
  { code: "776", name: "Tailandia" },
  { code: "780", name: "Tanzania" },
  { code: "783", name: "Djibouti" },
  { code: "787", name: "Territorio Británico del Océano Índico" },
  { code: "788", name: "Timor del Este" },
  { code: "800", name: "Togo" },
  { code: "805", name: "Tokelau" },
  { code: "810", name: "Tonga" },
  { code: "815", name: "Trinidad y Tobago" },
  { code: "820", name: "Túnez" },
  { code: "823", name: "Turcas y Caicos, Islas" },
  { code: "825", name: "Turkmenistán" },
  { code: "827", name: "Turquía" },
  { code: "828", name: "Tuvalu" },
  { code: "830", name: "Ucrania" },
  { code: "833", name: "Uganda" },
  { code: "845", name: "Uruguay" },
  { code: "847", name: "Uzbekistán" },
  { code: "850", name: "Venezuela" },
  { code: "855", name: "Vietnam" },
  { code: "863", name: "Vírgenes, Islas (Británicas)" },
  { code: "866", name: "Vírgenes, Islas (Norteamericanas)" },
  { code: "870", name: "Fiji" },
  { code: "875", name: "Wallis y Fortuna, Islas" },
  { code: "880", name: "Yemen" },
  { code: "885", name: "Yugoslavia" },
  { code: "888", name: "Zaire" },
  { code: "890", name: "Zambia" },
  { code: "897", name: "Zona Neutral Palestina" },
] as const;

export type DianCountryCode = typeof DIAN_COUNTRIES[number]["code"];

export function getCountryName(code: string): string {
  const country = DIAN_COUNTRIES.find(c => c.code === code);
  return country?.name || code;
}

export function getCountryCode(name: string): string | undefined {
  const country = DIAN_COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
  return country?.code;
}
