export interface PhoneCountryCode {
  code: string;
  country: string;
  flag: string;
}

export const PHONE_COUNTRY_CODES: PhoneCountryCode[] = [
  { code: "57", country: "Colombia", flag: "CO" },
  { code: "1", country: "Estados Unidos", flag: "US" },
  { code: "52", country: "México", flag: "MX" },
  { code: "54", country: "Argentina", flag: "AR" },
  { code: "56", country: "Chile", flag: "CL" },
  { code: "51", country: "Perú", flag: "PE" },
  { code: "593", country: "Ecuador", flag: "EC" },
  { code: "58", country: "Venezuela", flag: "VE" },
  { code: "591", country: "Bolivia", flag: "BO" },
  { code: "595", country: "Paraguay", flag: "PY" },
  { code: "598", country: "Uruguay", flag: "UY" },
  { code: "507", country: "Panamá", flag: "PA" },
  { code: "506", country: "Costa Rica", flag: "CR" },
  { code: "502", country: "Guatemala", flag: "GT" },
  { code: "503", country: "El Salvador", flag: "SV" },
  { code: "504", country: "Honduras", flag: "HN" },
  { code: "505", country: "Nicaragua", flag: "NI" },
  { code: "53", country: "Cuba", flag: "CU" },
  { code: "1809", country: "Rep. Dominicana", flag: "DO" },
  { code: "34", country: "España", flag: "ES" },
  { code: "55", country: "Brasil", flag: "BR" },
  { code: "44", country: "Reino Unido", flag: "GB" },
  { code: "33", country: "Francia", flag: "FR" },
  { code: "49", country: "Alemania", flag: "DE" },
  { code: "39", country: "Italia", flag: "IT" },
  { code: "351", country: "Portugal", flag: "PT" },
  { code: "81", country: "Japón", flag: "JP" },
  { code: "86", country: "China", flag: "CN" },
  { code: "91", country: "India", flag: "IN" },
  { code: "82", country: "Corea del Sur", flag: "KR" },
  { code: "61", country: "Australia", flag: "AU" },
  { code: "7", country: "Rusia", flag: "RU" },
  { code: "27", country: "Sudáfrica", flag: "ZA" },
  { code: "234", country: "Nigeria", flag: "NG" },
  { code: "254", country: "Kenia", flag: "KE" },
  { code: "20", country: "Egipto", flag: "EG" },
  { code: "971", country: "Emiratos Árabes", flag: "AE" },
  { code: "966", country: "Arabia Saudita", flag: "SA" },
  { code: "90", country: "Turquía", flag: "TR" },
  { code: "48", country: "Polonia", flag: "PL" },
  { code: "46", country: "Suecia", flag: "SE" },
  { code: "41", country: "Suiza", flag: "CH" },
  { code: "31", country: "Países Bajos", flag: "NL" },
  { code: "32", country: "Bélgica", flag: "BE" },
  { code: "43", country: "Austria", flag: "AT" },
  { code: "353", country: "Irlanda", flag: "IE" },
  { code: "47", country: "Noruega", flag: "NO" },
  { code: "45", country: "Dinamarca", flag: "DK" },
  { code: "358", country: "Finlandia", flag: "FI" },
  { code: "30", country: "Grecia", flag: "GR" },
  { code: "380", country: "Ucrania", flag: "UA" },
  { code: "40", country: "Rumanía", flag: "RO" },
  { code: "420", country: "República Checa", flag: "CZ" },
  { code: "36", country: "Hungría", flag: "HU" },
  { code: "972", country: "Israel", flag: "IL" },
  { code: "65", country: "Singapur", flag: "SG" },
  { code: "60", country: "Malasia", flag: "MY" },
  { code: "66", country: "Tailandia", flag: "TH" },
  { code: "84", country: "Vietnam", flag: "VN" },
  { code: "63", country: "Filipinas", flag: "PH" },
  { code: "62", country: "Indonesia", flag: "ID" },
  { code: "64", country: "Nueva Zelanda", flag: "NZ" },
];
